sudo: false
language: python
python:
 - "3.4"
 - "3.5"
env:
  global:
  matrix:
install:
 - pip install django
 - pip install flake8
 - pip install python-coveralls
branches:
 only:
  - master
script:
 - coverage run --source=試驗中介 manage.py test
 - flake8 .
matrix:
after_success:
  - coverage report
  - coveralls
